### ISSUE TITLE
Translation PT-BR

### ISSUE THREAD

**Issue by rodopoulos1** [RonanLOUARN/Map-Cycle#13]
Translation PT-BR is incorrect, here is the new version:
[pt-BR.json](https://github.com/RonanLOUARN/Map-Cycle/files/14059638/pt-BR.json)

**Comment by RonanLOUARN** [comment]
Done in v-1.4.2

**Comment by rodopoulos1** [comment]
Translation PT-BR Update 1.4.3
[pt-BR.json](https://github.com/RonanLOUARN/Map-Cycle/files/14091821/pt-BR.json)
