### ISSUE TITLE
[REQ] Improvements to the `!go` command

### ISSUE THREAD

**Issue by crashzk** [RonanLOUARN/Map-Cycle#15]
Implement the option to choose the next direct map in the `!go` command, without having to change the map in the `!nextmap` command.

Example, using the command `!nextmap` shows that the next map would be `de_nuke`, but players don't want to play this map, so using the command `!go de_vertigo` it would switch directly to the de_vertigo map skipping the map cycle and without the need to use the `!nextmap de_vertigo` command and then the `!go` command to change the `de_vertigo` map.

It would be possible?

Anyway, it would be implementing the option in the `!go` command to have the option to choose the map if you want. `!go de_vertigo` and if you just use `!go` it simply switches to the next map in the cycle normally, as it is now.

**Comment by RonanLOUARN** [comment]
**!goto cs_assault**: This command allows direct access to a chosen map (de_dust2 in this case) in your cycle, bypassing the need to wait for the current match to end. You can also go to a map workshop ID using the command !goto 123123123, even if it's not in the cycle.
