### ISSUE TITLE
Change name of Portuguese translation file

### ISSUE THREAD

**Issue by crashzk** [RonanLOUARN/Map-Cycle#9]
I believe you need to change to pt-BR and pt-PT.

- `pt-BR` = For Brazilian Portuguese translations
- `pt-PT` = For Portuguese translations from Portugal

From what I understand they are keeping everything in one format: https://learn.microsoft.com/en-us/bingmaps/rest-services/common-parameters-and-types/supported-culture-codes

**Comment by RonanLOUARN** [comment]
Great ! Thanks for your feedback.
I didn't know.
I'll correct it ASAP.

**Comment by RonanLOUARN** [comment]
https://github.com/RonanLOUARN/Map-Cycle/releases/tag/release-v-1.3.0
